heuristic_rules:
  min_score: 2
  kbs:
    edu:
      keywords:
        - 学生
        - 学籍
        - 退学
        - 旷课
        - 学时
        - 学分
        - 课程
        - 考试
        - 成绩
        - 补考
        - 重修
        - 请假
        - 辅导员
        - 班级
        - 宿舍
        - 处分
        - 毕业
        - 选课
        - 挂科
    movie:
      keywords:
        - 电影
        - 影片
        - 导演
        - 主演
        - 演员
        - 编剧
        - 票房
        - 上映
        - 片长
        - 评分
        - 豆瓣
        - imdb
        - 科幻
        - 剧情
        - 喜剧
        - 动作
        - 恐怖
